<?php
	GLOBAL $GLOBS;
	GLOBAL $MYSQLI;
	
	INCLUDE $_SERVER['DOCUMENT_ROOT'] . '/vault/config.php';
	INCLUDE ROOT . 'admin/vault/lib.php';
	INCLUDE_ONCE ROOT . 'admin/vault/ini.class.php';
		
	SESSION_START();
	
	$QUERY = @$_GET['query'];
	$DATA = JSON_DECODE(FILE_GET_CONTENTS('php://input'));
	$MYSQLI = DB::CONNECT();
	
	IF($MYSQLI->connect_errno) {
		DIE('{"responce": "ERROR"}');
	}
	
	$GLOBS = GLOBS::GET();
			
	$NORIGHTS = '{"responce": "NORIGHTS"}';
	$RESTRICTED = '{"responce": "RESTRICTED"}';
	$UNKNOWN = '{"responce": "UNKNOWN"}';
	
	IF(!ISSET($_GET['query'])) {
		ECHO $RESTRICTED;
		EXIT;
	}
		
	
	// SIGN IN
	IF($QUERY == 'SIGNIN') {			
		ECHO AUTH::SIGNIN($DATA);					
		EXIT;
	}
	
	// CHEK USER
	$AUTH = AUTH::CHECK();
	$ISUSER = $AUTH['exist'] == TRUE AND $AUTH['user']->status == 1;
	$ISADMIN = $AUTH['user']->rights >= 1;
	$ISSUPERADMIN = $AUTH['user']->rights == 2;

	IF(!$ISUSER) {
		ECHO $RESTRICTED;
		EXIT;
	}
		
	SWITCH($QUERY) {				
		// LOGIN
		CASE 'SIGNOUT': ECHO AUTH::SIGNOUT(); BREAK;
		// CAT
		//CASE 'CATGET': ECHO $ISSUPERADMIN ? CAT::GET($DATA) : $NORIGHTS;
		CASE 'CATGET': ECHO CAT::GETTREE();	BREAK;
		CASE 'GETTREE': ECHO $ISADMIN ? CAT::GETTREE() : $NORIGHTS; BREAK;	
		CASE 'CATSETPARAM': ECHO $ISADMIN ? CAT::CATSETPARAM($DATA) : $NORIGHTS; BREAK;
		CASE 'CATDEL': ECHO $ISADMIN ? CAT::DEL($DATA) : $NORIGHTS;	BREAK;
		CASE 'CATADD': ECHO $ISADMIN ? CAT::ADD($DATA) : $NORIGHTS;	BREAK;
		CASE 'CATSORT': ECHO $ISSUPERADMIN ? CAT::SORTORDER($DATA) : $NORIGHTS;	BREAK;
		CASE 'CATRENAME': ECHO $ISADMIN ? CAT::REN($DATA) : $NORIGHTS; BREAK;
		CASE 'CATTOGGLEEDITOR': ECHO $ISSUPERADMIN ? CAT::CATTOGGLEEDITOR($DATA) : $NORIGHTS; BREAK;
		CASE 'CATDELDITOR': ECHO $ISSUPERADMIN ? CAT::CATDELDITOR($DATA) : $NORIGHTS; BREAK;
		CASE 'CATADDGRP': ECHO $ISSUPERADMIN ? CAT::CATADDGRP($DATA) : $NORIGHTS; BREAK;
		CASE 'CATDELGRP': ECHO $ISSUPERADMIN ? CAT::CATDELGRP($DATA) : $NORIGHTS; BREAK;
		CASE 'CATTOGGLEGRP': ECHO $ISSUPERADMIN ? CAT::CATTOGGLEGRP($DATA) : $NORIGHTS; BREAK;
		// TAGS
		CASE 'TAGSGET': ECHO $ISSUPERADMIN ? TAGS::GET($DATA) : $NORIGHTS; BREAK;
		CASE 'TAGSDEL': ECHO $ISSUPERADMIN ? TAGS::DEL($DATA) : $NORIGHTS; BREAK;
		CASE 'TAGSCHANGE': ECHO $ISSUPERADMIN ? TAGS::CHANGE($DATA) : $NORIGHTS; BREAK;
		CASE 'TAGSREFRESH': ECHO $ISSUPERADMIN ? TAGS::REFRESH($DATA) : $NORIGHTS; BREAK;
		// MAIL
		CASE 'SENDEMAIL': ECHO $ISSUPERADMIN ? EMAILSYSTEM::SENDMAIL($DATA) : $NORIGHTS; BREAK;
		// DASHBOARD
		CASE 'DASHBOARDINFO': ECHO $ISADMIN ? DASHBOARD::INFO() : $NORIGHTS; BREAK;
		CASE 'DOWNLOADLOGGET': ECHO $ISADMIN ? DASHBOARD::DOWNLOADLOG($DATA) : $NORIGHTS; BREAK;
		// COMMENTS
		CASE 'COMMENTSGET': ECHO $ISADMIN ? COMMENTS::GET($DATA) : $NORIGHTS; BREAK;
		CASE 'COMMENTSDEL': ECHO $ISADMIN ? COMMENTS::DEL($DATA) : $NORIGHTS; BREAK;
		// PROD			
		CASE 'PRODGET': ECHO $ISADMIN ? PRODUCTS::GET($DATA) : $NORIGHTS; BREAK;
		CASE 'PRODINFO': ECHO $ISADMIN ? PRODUCTS::PRODUCTINFO($DATA) : $NORIGHTS; BREAK;
		CASE 'PRODSETPARAM': ECHO $ISADMIN ? PRODUCTS::PRODSETPARAM($DATA) : $NORIGHTS;	BREAK;
		CASE 'PRODTOGGLEPARAM': ECHO $ISADMIN ? PRODUCTS::PRODTOGGLEPARAM($DATA) : $NORIGHTS;	BREAK;
		CASE 'PRODSETTEXTPARAM': ECHO $ISADMIN ? PRODUCTS::PRODSETTEXTPARAM($DATA) : $NORIGHTS;	BREAK;
		CASE 'PRODSETNAME': ECHO $ISADMIN ? PRODUCTS::PRODSETNAME($DATA) : $NORIGHTS; BREAK;
		CASE 'PRODSETOVERVIEW': ECHO $ISADMIN ? PRODUCTS::PRODSETOVERVIEW($DATA) : $NORIGHTS; BREAK;
		CASE 'PRODREMOVETAG': ECHO $ISADMIN ? PRODUCTS::PRODREMOVETAG($DATA) : $NORIGHTS; BREAK;
		CASE 'PRODADDTAGS': ECHO $ISADMIN ? PRODUCTS::PRODADDTAGS($DATA) : $NORIGHTS; BREAK;
		CASE 'PRODSETMAINPREVIEW': ECHO $ISADMIN ? PRODUCTS::PRODSETMAINPREVIEW($DATA) : $NORIGHTS;	BREAK;
		CASE 'PRODDELPREVIEW': ECHO $ISADMIN ? PRODUCTS::PRODDELPREVIEW($DATA) : $NORIGHTS;	BREAK;
		CASE 'PRODDELETE': ECHO $ISADMIN ? PRODUCTS::PRODDELETE($DATA) : $NORIGHTS;	BREAK;
		CASE 'PRODREMOVEWEBGL': ECHO $ISADMIN ? PRODUCTS::PRODREMOVEWEBGL($DATA) : $NORIGHTS; BREAK;	
		CASE 'PRODMOVE': ECHO $ISSUPERADMIN ? PRODUCTS::PRODMOVE($DATA) : $NORIGHTS; BREAK;	
		// MSG
		CASE 'MSGGETCNT': ECHO $ISADMIN ? MSGSYSTEM::GETCNT() : $NORIGHTS; BREAK;
		CASE 'MSGGET': ECHO $ISADMIN ? MSGSYSTEM::GET($DATA) : $NORIGHTS; BREAK;
		CASE 'MSGSETPARAM': ECHO $ISADMIN ? MSGSYSTEM::SETPARAM($DATA) : $NORIGHTS; BREAK;
		CASE 'MSGDELETE': ECHO $ISADMIN ? MSGSYSTEM::DEL($DATA) : $NORIGHTS; BREAK;
		//USERS
		CASE 'USERSGET': ECHO USERS::GET($DATA); BREAK;
		CASE 'USERSETPARAM': ECHO $ISSUPERADMIN ? USERS::USERETPARAM($DATA) : $NORIGHTS;BREAK;
		CASE 'USERISINFO': ECHO $ISSUPERADMIN ? USERS::USERINFO($DATA) : $NORIGHTS;	BREAK;
		CASE 'USERGETFILTER': ECHO $ISADMIN ? USERS::USERGETFILTER() : $NORIGHTS; BREAK;		
		// GLOBAL
		CASE 'GLOBALGET': ECHO $GLOBS; BREAK;
		CASE 'GLOBALCHANGE': ECHO $ISSUPERADMIN ? GLOBS::ADD($DATA) : $NORIGHTS; BREAK;	
		// GROUPS
		CASE 'GETGROUPS': ECHO $ISSUPERADMIN ? USERS::GETGROUPS($DATA) : $NORIGHTS;	BREAK;
		CASE 'GROUPADD': ECHO $ISSUPERADMIN ? USERS::GROUPADD($DATA) : $NORIGHTS; BREAK;
		CASE 'GROUPDEL': ECHO $ISSUPERADMIN ? USERS::GROUPDEL($DATA) : $NORIGHTS; BREAK;
		CASE 'GROUPRENAME': ECHO $ISSUPERADMIN ? USERS::GROUPRENAME($DATA) : $NORIGHTS; BREAK;	
		CASE 'GROUPTOGGLE': ECHO $ISSUPERADMIN ? USERS::GROUPTOGGLE($DATA) : $NORIGHTS; BREAK;	
		// BACKUP
		CASE 'ADMINBACKUPDB': ECHO $ISSUPERADMIN ? BACKUP::DB($DATA) : $NORIGHTS; BREAK;	
		CASE 'GETBACKUPLIST': ECHO $ISSUPERADMIN ? BACKUP::GETLISTDB($DATA) : $NORIGHTS; BREAK;	
		CASE 'DELETEBACKUP': ECHO $ISSUPERADMIN ? BACKUP::DELDB($DATA) : $NORIGHTS; BREAK;	
		// MISSING
		CASE 'ADMINBFINDMISSING': ECHO $ISSUPERADMIN ? MISSING::FIND($DATA) : $NORIGHTS; BREAK;	
		CASE 'ADMINDELETEMISSING': ECHO $ISSUPERADMIN ? MISSING::DEL($DATA) : $NORIGHTS; BREAK;	
		
		// DEF
		DEFAULT: ECHO $UNKNOWN;
		BREAK;
	}					
		
	DB::CLOSE();
	
	EXIT();
?>