<?php
	GLOBAL $GLOBS;
	GLOBAL $MYSQLI;
	
	INCLUDE 'config.php';
	INCLUDE 'lib.php';
	
	SESSION_START();
	
	$QUERY = @$_GET['query'];
	$DATA = JSON_DECODE(FILE_GET_CONTENTS('php://input'));
	$MYSQLI = DB::CONNECT();
	
	IF($MYSQLI->connect_errno) {
		DIE('{"responce": "ERROR"}');
	}
	
	$GLOBS = GLOBS::GET();
			
	$NORIGHTS = '{"responce": "NORIGHTS"}';
	$RESTRICTED = '{"responce": "RESTRICTED"}';
	$UNKNOWN = '{"responce": "UNKNOWN"}';
	
	IF(!ISSET($_GET['query'])) {
		ECHO $RESTRICTED;
		EXIT;
	}
		
	
	// SIGN IN
	IF($QUERY == 'SIGNIN') {			
		ECHO AUTH::SIGNIN($DATA);					
		EXIT;
	}
	
	// CHEK USER
	$AUTH = AUTH::CHECK();
	$ISALLOW = $AUTH['user']->status == 1;
	$ISUSER =  $AUTH['user']->rights >= 0;
	$ISADMIN = $AUTH['user']->rights >= 1;
	$ISSUPERADMIN = $AUTH['user']->rights == 2;

	IF(!$ISALLOW) {
		DIE($RESTRICTED);	
		EXIT;
	}
		
	SWITCH($QUERY) {				
		// LOGIN
		CASE 'SIGNOUT': ECHO AUTH::SIGNOUT();
		BREAK;		
		CASE 'CATGET': ECHO CAT::GETTREE();
		BREAK;				
		// GLOBAL
		CASE 'GLOBALGET': ECHO $GLOBS;
		BREAK;
		// AUTH
		CASE 'GETAUTH': ECHO AUTH::GETAUTH();
		BREAK;
		CASE 'GETUSERPROFILE': ECHO AUTH::GETUSERPROFILE($DATA);
		BREAK;
		// AVATAR
		CASE 'DELAVATAR': ECHO AVATAR::CLEAR();
		BREAK;
		//	HOME
		CASE 'HOMEGET': ECHO HOME::GET($DATA);
		BREAK;
		// PRODUCTS
		CASE 'PRODGET': ECHO PRODUCTS::GET($DATA);
		BREAK;
		CASE 'PRODINFO': ECHO PRODUCTS::INFO($DATA);
		BREAK;
		CASE 'PRODRATE': ECHO PRODUCTS::RATE($DATA);
		BREAK;
		CASE 'SENDCOMMENT': ECHO PRODUCTS::SENDCOMMENT($DATA);
		BREAK;
		CASE 'GETCOMMENTS': ECHO PRODUCTS::GETCOMMENTS($DATA);
		BREAK;
		CASE 'DELCOMMENT': ECHO PRODUCTS::DELCOMMENT($DATA);
		BREAK;
		CASE 'FEEDBACK': ECHO MSGSYSTEM::FEEDBACK($DATA);
		BREAK;
		CASE 'DOWNLOADMODEL': ECHO $ISUSER ? PRODUCTS::MODELDOWNLOAD($DATA) : $NORIGHTS;
		BREAK;
		CASE 'CHECKPENDING': ECHO $ISADMIN ? PRODUCTS::CHECKPENDING($DATA) : $NORIGHTS;
		BREAK;
		// MXS
		CASE 'ADDMODEL': ECHO $ISUSER ? MXS::ADDMODEL($DATA) : $NORIGHTS;
		BREAK;
		// SEARCH
		CASE 'FASTSEARCH': ECHO SEARCH::GLOBALSEARCH($DATA, TRUE);
		BREAK;
		CASE 'GLOBALSEARCH': ECHO SEARCH::GLOBALSEARCH($DATA);
		BREAK;	
		// FAV
		CASE 'FAVGET': ECHO FAVORITES::GET($DATA);
		BREAK;
		CASE 'FAVNEWCOLLECTION': ECHO FAVORITES::NEWCOLLECTION($DATA);
		BREAK;
		CASE 'FAVSHARECOLLECTION': ECHO FAVORITES::SHARECOLLECTION($DATA);
		BREAK;
		CASE 'FAVGETSHARED': ECHO FAVORITES::GETSHARED($DATA);
		BREAK;
		CASE 'FAVDELCOLLECTION': ECHO FAVORITES::DELCOLLECTION($DATA);
		BREAK;
		CASE 'FAVRENAMECOLLECTION': ECHO FAVORITES::RENCOLLECTION($DATA);
		BREAK;
		CASE 'FAVADDITEM': ECHO FAVORITES::ADDITEM($DATA);
		BREAK;
		CASE 'FAVDELITEM': ECHO FAVORITES::REMOVEITEM($DATA);
		BREAK;
		CASE 'FAVGETCOLLECTION': ECHO FAVORITES::GETCOLLECTION($DATA);
		BREAK;
		// DEF
		DEFAULT: ECHO $UNKNOWN;
		BREAK;
		
		
	}					
		
	DB::CLOSE();
?>