<?php
	GLOBAL $GLOBS;
	GLOBAL $MYSQLI;
	
	INCLUDE 'config.php';
	INCLUDE 'lib.php';
	
	SESSION_START();
	
	$QUERY = @$_GET['query'];
	$DATA = JSON_DECODE(FILE_GET_CONTENTS('php://input'));
	$MYSQLI = DB::CONNECT();
	
	IF($MYSQLI->connect_errno) {
		DIE('{"responce": "ERROR"}');
	}
	
	$GLOBS = GLOBS::GET();
			
	$NORIGHTS = '{"responce": "NORIGHTS"}';
	$RESTRICTED = '{"responce": "RESTRICTED"}';
	$UNKNOWN = '{"responce": "UNKNOWN"}';
	
	IF(!ISSET($_GET['query'])) {
		ECHO $RESTRICTED;
		EXIT;
	}
		
	
	// SIGN IN
	IF($QUERY == 'SIGNIN') {			
		ECHO AUTH::SIGNIN($DATA);					
		EXIT;
	}
	
	// CHEK USER
	$AUTH = AUTH::CHECK();
	$ISUSER = $AUTH['exist'] == TRUE AND $AUTH['user']->status == 1;
	$ISADMIN = $AUTH['user']->rights >= 1;
	$ISSUPERADMIN = $AUTH['user']->rights == 2;

	IF(!$ISUSER) {
		ECHO $RESTRICTED;
		EXIT;
	}
		
	SWITCH($QUERY) {				
		// LOGIN
		CASE 'SIGNOUT': ECHO AUTH::SIGNOUT();
		BREAK;
		// CAT
		//CASE 'CATGET': ECHO $ISSUPERADMIN ? CAT::GET($DATA) : $NORIGHTS;
		CASE 'CATGET': ECHO CAT::GETTREE();
		BREAK;
		CASE 'GETTREE': ECHO $ISSUPERADMIN ? CAT::GETTREE() : $NORIGHTS;
		BREAK;	
		CASE 'CATSETPARAM': ECHO $ISSUPERADMIN ? CAT::CATSETPARAM($DATA) : $NORIGHTS;
		BREAK;
		CASE 'CATDEL': ECHO $ISSUPERADMIN ? CAT::DEL($DATA) : $NORIGHTS;
		BREAK;
		CASE 'CATADD': ECHO $ISSUPERADMIN ? CAT::ADD($DATA) : $NORIGHTS;
		BREAK;
		CASE 'CATSORT': ECHO $ISSUPERADMIN ? CAT::SORTORDER($DATA) : $NORIGHTS;
		BREAK;
		CASE 'CATRENAME': ECHO $ISSUPERADMIN ? CAT::REN($DATA) : $NORIGHTS;
		BREAK;
		// PROD
		CASE 'PRODGET': ECHO PRODUCTS::GET($DATA);
		BREAK;
		CASE 'PRODINFO': ECHO PRODUCTS::PRODUCTINFO($DATA);
		BREAK;
		CASE 'PRODSETPARAM': ECHO $ISSUPERADMIN ? PRODUCTS::PRODSETPARAM($DATA) : $NORIGHTS;
		BREAK;
		CASE 'PRODSETNAME': ECHO $ISSUPERADMIN ? PRODUCTS::PRODSETNAME($DATA) : $NORIGHTS;
		BREAK;
		CASE 'PRODSETOVERVIEW': ECHO $ISSUPERADMIN ? PRODUCTS::PRODSETOVERVIEW($DATA) : $NORIGHTS;
		BREAK;
		CASE 'PRODREMOVETAG': ECHO $ISSUPERADMIN ? PRODUCTS::PRODREMOVETAG($DATA) : $NORIGHTS;
		BREAK;
		CASE 'PRODADDTAGS': ECHO $ISSUPERADMIN ? PRODUCTS::PRODADDTAGS($DATA) : $NORIGHTS;
		BREAK;
		CASE 'PRODSETMAINPREVIEW': ECHO $ISSUPERADMIN ? PRODUCTS::PRODSETMAINPREVIEW($DATA) : $NORIGHTS;
		BREAK;
		CASE 'PRODDELPREVIEW': ECHO $ISSUPERADMIN ? PRODUCTS::PRODDELPREVIEW($DATA) : $NORIGHTS;
		BREAK;
		CASE 'PRODDELETE': ECHO $ISSUPERADMIN ? PRODUCTS::PRODDELETE($DATA) : $NORIGHTS;
		BREAK;
		// GLOBAL
		CASE 'GLOBALGET': ECHO $GLOBS;
		BREAK;
		CASE 'GLOBALCHANGE': ECHO $ISSUPERADMIN ? GLOBS::ADD($DATA) : $NORIGHTS;
		BREAK;		
		// DEF
		DEFAULT: ECHO $UNKNOWN;
		BREAK;
	}					
		
	DB::CLOSE();
?>